### ISSUE TITLE
config for spoil time

### ISSUE THREAD

**Issue by Douche-Box** [Globox1997/SpoiledZ#6]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

config for spoil time plz? :)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/SpoiledZ/commit/4d8a46778354536393d8d7caaa6d9d4a974286aa](https://github.com/Globox1997/SpoiledZ/commit/4d8a46778354536393d8d7caaa6d9d4a974286aa)
