### ISSUE TITLE
Crashes With Farmers delight

### ISSUE THREAD

**Issue by LegendarySpy** [Globox1997/SpoiledZ#8]
### Minecraft Version

1.20.x

### Mod Loader Version

Quilt - 0.20.0 Beta 5

### Mod Version

1.20 - 1.07

### Crashes on startup when paired with Farmer's Delight and works fine without Farmer's Delight

**My guess is this is whats breaking / missing :** 

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#spoiledz:spoiledz.mixins.json:compat.CookingPotBlockEntityMixin from mod spoiledz] from phase [DEFAULT] in config [#spoiledz:spoiledz.mixins.json] FAILED during APPLY

### latest.log

[latest.log](https://github.com/Globox1997/SpoiledZ/files/12254421/latest.log)

### Do you use any other mods except the required ones?

Farmer's Delight and many others, none of which seem to effect it

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/SpoiledZ/commit/afc6fab67cb6ffea7d032ae40e99968a8008bba5](https://github.com/Globox1997/SpoiledZ/commit/afc6fab67cb6ffea7d032ae40e99968a8008bba5)

**Comment by Ashlytical** [comment]
Would a fix be happening for 1.19.2 as-well?

**Comment by Mark1ed** [comment]
> Would a fix be happening for 1.19.2 as-well?

Hope so because i need it for my modpack (1.0.8 for 1.19.2) @Globox1997

**Comment by timkicker** [comment]
Just wanted to ask if a fix is in plan for 1.19.2 and 1.19.4 since a lot of modpacks would like to use both of those amazing mods :)
